"""Create initial tables

Revision ID: de136d573169
Revises: 
Create Date: 2025-04-08 14:30:18.744234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de136d573169'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=False)
    op.create_table('material_color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_material_color_id'), 'material_color', ['id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PROFILE', 'KLAMER', 'BRACKET', 'EXTENSION_BRACKET', 'CASSETTE', 'FACING', 'LINEAR_PANEL', 'SHEET', 'WALL_PANEL', 'OTHER', name='producttypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_table('profile_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_profile_type_id'), 'profile_type', ['id'], unique=False)
    op.create_table('sheet_length',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('length')
    )
    op.create_index(op.f('ix_sheet_length_id'), 'sheet_length', ['id'], unique=False)
    op.create_table('sheet_width',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('width', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('width')
    )
    op.create_index(op.f('ix_sheet_width_id'), 'sheet_width', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telegram', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('user_type', sa.Enum('ADMIN', 'ENGINEER', 'OPERATOR', 'SUPERVISER', name='usertypeenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('workshop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('PROFILE', 'KLAMER', 'BRACKET', 'EXTENSION_BRACKET', 'ENGINEER', 'BENDING', 'CUTTING', 'COORDINATE_PUNCHING', 'PAINTING', name='workshopenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_id'), 'workshop', ['id'], unique=False)
    op.create_table('bid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_number', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('manager', sa.Enum('NOVIKOV', 'SEMICHEV', 'PTICHKINA', 'VIKULINA', 'GAVRILOVEC', 'SEMICHEV_YOUNGER', name='managerenum'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_id'), 'bid', ['id'], unique=False)
    op.create_table('bracket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('length', sa.String(length=50), nullable=False),
    sa.Column('thickness', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bracket_id'), 'bracket', ['id'], unique=False)
    op.create_table('cassette',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('cassette_type', sa.Enum('KZT_STD', 'KOT_STD', 'KOTVO', 'KZT', 'KOT', 'OTHER', name='cassettetypeenum'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cassette_id'), 'cassette', ['id'], unique=False)
    op.create_table('extension_bracket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('length', sa.String(length=50), nullable=False),
    sa.Column('heel', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_bracket_id'), 'extension_bracket', ['id'], unique=False)
    op.create_table('klamer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('IN_LINE', 'STARTING', 'ANGULAR', name='klamertypeenum'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_klamer_id'), 'klamer', ['id'], unique=False)
    op.create_table('linear_panel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('rust', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('butt_end', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linear_panel_id'), 'linear_panel', ['id'], unique=False)
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form', sa.Enum('SHEET', 'COIL', 'STRIP', name='materialformenum'), nullable=False),
    sa.Column('type', sa.Enum('ALUMINIUM', 'STEEL', 'STAINLESS_STEEL', 'ZINC', 'POLYMER', name='materialtypeenum'), nullable=False),
    sa.Column('thickness', sa.Enum('ZERO_FIVE', 'ZERO_SEVEN', 'ONE', 'ONE_TWO', 'ONE_FIVE', 'TWO', 'THREE', name='materialthicknessenum'), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('painting', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['material_color.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_id'), 'material', ['id'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('profile_type_id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['profile_type_id'], ['profile_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_id'), 'profile', ['id'], unique=False)
    op.create_table('user_workshop_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'workshop_id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('urgency', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='urgencyenum'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_WORK', 'COMPLETED', 'CANCELED', 'ON_HOLD', name='statusenum'), nullable=True),
    sa.Column('waste', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bid.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_id'), 'comment', ['id'], unique=False)
    op.create_table('sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('width_sheet', sa.Integer(), nullable=False),
    sa.Column('length_sheet', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['length_sheet'], ['sheet_length.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['width_sheet'], ['sheet_width.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sheets_id'), 'sheets', ['id'], unique=False)
    op.create_table('task_responsible_association',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.create_table('task_workshops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('workshop_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_WORK', 'COMPLETED', 'CANCELED', 'ON_HOLD', name='statusenum'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_workshops_id'), 'task_workshops', ['id'], unique=False)
    op.create_table('comment_user_association',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_user_association')
    op.drop_index(op.f('ix_task_workshops_id'), table_name='task_workshops')
    op.drop_table('task_workshops')
    op.drop_table('task_responsible_association')
    op.drop_index(op.f('ix_sheets_id'), table_name='sheets')
    op.drop_table('sheets')
    op.drop_index(op.f('ix_comment_id'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    op.drop_table('user_workshop_association')
    op.drop_index(op.f('ix_profile_id'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_material_id'), table_name='material')
    op.drop_table('material')
    op.drop_index(op.f('ix_linear_panel_id'), table_name='linear_panel')
    op.drop_table('linear_panel')
    op.drop_index(op.f('ix_klamer_id'), table_name='klamer')
    op.drop_table('klamer')
    op.drop_index(op.f('ix_extension_bracket_id'), table_name='extension_bracket')
    op.drop_table('extension_bracket')
    op.drop_index(op.f('ix_cassette_id'), table_name='cassette')
    op.drop_table('cassette')
    op.drop_index(op.f('ix_bracket_id'), table_name='bracket')
    op.drop_table('bracket')
    op.drop_index(op.f('ix_bid_id'), table_name='bid')
    op.drop_table('bid')
    op.drop_index(op.f('ix_workshop_id'), table_name='workshop')
    op.drop_table('workshop')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sheet_width_id'), table_name='sheet_width')
    op.drop_table('sheet_width')
    op.drop_index(op.f('ix_sheet_length_id'), table_name='sheet_length')
    op.drop_table('sheet_length')
    op.drop_index(op.f('ix_profile_type_id'), table_name='profile_type')
    op.drop_table('profile_type')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_material_color_id'), table_name='material_color')
    op.drop_table('material_color')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
