"""Create initial tables

Revision ID: e939ac890dd5
Revises: 6595be819b9c
Create Date: 2025-04-14 11:11:12.182872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'e939ac890dd5'
down_revision: Union[str, None] = '6595be819b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('data', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###
